services:
  postgres:
    image: postgres:17-bookworm
    container_name: postgres-db
    environment:
      POSTGRES_USER: wajavi
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./docker-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
  redis:
    image: redis:8.2-m01-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no



